version: "3.8"
services:
  hub:
    image: selenium/hub
    container_name: my-hub
    ports:
      - "4444:4444"
    networks:
      - my-network
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - my-network
  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - my-network

networks:
  my-network:
    name: docker-grid